### ISSUE TITLE
希望能添加一些图像识别的接口

### ISSUE THREAD

**Issue by xyhere2001** [TencentCloud/tencentcloud-sdk-dotnet#12]
比如驾驶证识别，还是2.0的SDK，也没有.net的版本，我自己也进行了一些从javd SDK到.net 的转换，还是希望官方能支持，谢谢！

**Comment by zqfan** [comment]
tencentcloud-sdk-*里只有api3.0的接口，dotnet sdk的接口和tencentcloud-sdk-java里的都是一样的。你可以贴一下java sdk里的具体的链接看看

**Comment by xyhere2001** [comment]
https://github.com/tencentyun/image-java-sdk-v2.0/blob/0fa49abec0713407f35b2e57a1a0e20324754b5d/src/main/java/com/qcloud/image/request/OcrDrivingLicenceRequest.java

这个应该是之前老的SDK， 里面的API比如这个驾驶证识别能在 这边支持吗？

**Comment by zqfan** [comment]
OCR还未放出驾驶证识别的功能吧，https://cloud.tencent.com/document/product/866/33515 ，此SDK不会包含，如有需要请到官网控制台提单给OCR产品让他们在API3.0中支持此接口。
