### ISSUE TITLE
Strong name

### ISSUE THREAD

**Issue by zufuliu** [TencentCloud/tencentcloud-sdk-dotnet#15]
Referenced assembly 'TencentCloud, Version=3.0.27.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

**Comment by zqfan** [comment]
目前是没签名的，请问不签名对你的使用有什么影响？
现在通过nuget能直接下载和管理依赖，这个签名是否不是必须的？

**Comment by zufuliu** [comment]
影响不大。
