### ISSUE TITLE
Monitor里的DataPoint的Timestamp的类型为什么是float

### ISSUE THREAD

**Issue by wsy** [TencentCloud/tencentcloud-sdk-dotnet#16]
第一次见到float类型存储以毫秒为单位的timestamp的

**Comment by zqfan** [comment]
请到控制台工单咨询云监控业务。SDK只是被动和他们发布的接口文档内容保持一致。

**Comment by wsy** [comment]
Java版SDK用的文档跟.Net、Python、Go版本用的不一样么？
为啥Java版就在四个月之前从float改成了Long？
Python和Go版本的SDK，这个文件都是两个月前编辑的，比Java的“float改Long”的变更要晚。
https://github.com/TencentCloud/tencentcloud-sdk-java/commit/b8b0e92d857b6a27fc6ef0014ef36664dfe91ed2

我觉得这还是你们代码生成工具的Bug

**Comment by zqfan** [comment]
在sdk这里纠结是没有意义的，根源还是这个产品API的定义。如果文档中说是float，而java代码里是long，这对于使用者反而是好事，起码没有精度损失了，能够精确表达到秒，至少在java里对于这个时间戳字段是这样。通常这种不一致是因为发现了问题，所以被迫做了调整，只有极少数是SDK本身设计有问题，至少这个例子不是。
