### ISSUE TITLE
有个会造成程序无限等待的低级bug

### ISSUE THREAD

**Issue by qiywtc** [TencentCloud/tencentcloud-sdk-dotnet#17]
在TencentCloud.Common.Http.HttpConnection类的107行，使用的方法“AsResponse”，在WINFROM和控制台下可以正常请求，但在.net framework的站点（mvc or webapi）下会导致程序无限等待。
改成.GetAwaiter().GetResult()即可。

**Comment by zqfan** [comment]
这样的修改是不是就把一个异步的调用变成了同步的等待呢？这样是不是就会让页面其他控件也卡住在那里等待呢？有没有看过readme里的这个解释https://github.com/TencentCloud/tencentcloud-sdk-dotnet#%E5%90%8C%E6%AD%A5%E8%B0%83%E7%94%A8%E4%B8%8E%E5%BC%82%E6%AD%A5%E8%B0%83%E7%94%A8 ？

**Comment by qiywtc** [comment]
> 这样的修改是不是就把一个异步的调用变成了同步的等待呢？这样是不是就会让页面其他控件也卡住在那里等待呢？有没有看过readme里的这个解释https://github.com/TencentCloud/tencentcloud-sdk-dotnet#%E5%90%8C%E6%AD%A5%E8%B0%83%E7%94%A8%E4%B8%8E%E5%BC%82%E6%AD%A5%E8%B0%83%E7%94%A8 ？

是把异步变同步，不过我方法本来就是异步的，不存在把其它控件也卡住的情况。
看过那个解释了，只是有个问题是，你是不会卡住其它控件了，但这个功能没用了。
在功能失效的情况下，卡不卡已经是没有意义的了。
我调用这个功能的接口，在等待返回结果时，将会无限等待。

你也可以新建几个web项目来进行测试，各个写法都试一下。

**Comment by zqfan** [comment]
如果你的方法是异步的并用对了，就不存在无限等待。你所说的无限等待，是使用同步方法调用异步接口，上下文互相等待最终死锁造成的。那个链接给出了项目的源码，异步方式调用不存在功能没法用的问题。

**Comment by afresh** [comment]
`        // SDK异步接口
        private async Task<string> GetZones()
        {
                // 处理一些初始化工作
                // 发起调用
                DescribeZonesResponse resp = await client.DescribeZones(req);
                // 输出json格式的字符串回包
                return AbstractModel.ToJsonString(resp);
        }
        // 注意：这里是一个同步接口
        private void Button1_Click(object sender, EventArgs e)
        {
            var result = "";
            var t = Task.Run(() =>
            {
                // 同步方式调用，会卡住直到请求返回
                result = GetZones().ConfigureAwait(false).GetAwaiter().GetResult();
            });
            // 同步等待，会卡住直到线程返回
            t.Wait();
            textBox1.Text = result;
        }`
webform站点，写在一般处理程序中，同无限等待。用了这个方法，有时可以响应，有时就无限等待。因为用的nuget，而没有用源码，不明白到底是怎么回事，看来只能下载源码调试了。
