### ISSUE TITLE
support .net core3 ?

### ISSUE THREAD

**Issue by zqfan** [TencentCloud/tencentcloud-sdk-dotnet#20]
user feedback:

您好，我想咨询一下，目前.net core3的预览版已经发布到9了。正式版也会在9月底发布，但我们这腾讯云文档才显示支持到2.1。连2.2版本好像都没说支持。我目前正在基于netcore开发网络服务。但到时候腾讯云会尽快的给与netcore对应版本的支持么？或者说有什么对应的支持时间表么？

**Comment by geffzhang** [comment]
.NETStandard 2.0 是可以支持到.NET Core 3.1的，可以放心使用
