### ISSUE TITLE
TencentCloud.Tmt.V20180321.Models.TextTranslateRequest中需要增加UntransaltedText 属性

### ISSUE THREAD

**Issue by scwuchen** [TencentCloud/tencentcloud-sdk-dotnet#21]
/// <summary>
        /// 排除不需要翻译的文本
        /// </summary>
        [JsonProperty("UntranslatedText")]
        public string UntranslatedText { get; set; }

        /// <summary>
        /// 内部实现，用户禁止调用
        /// </summary>
        internal override void ToMap(Dictionary<string, string> map, string prefix)
        {
            this.SetParamSimple(map, prefix + "SourceText", this.SourceText);
            this.SetParamSimple(map, prefix + "Source", this.Source);
            this.SetParamSimple(map, prefix + "Target", this.Target);
            this.SetParamSimple(map, prefix + "ProjectId", this.ProjectId);
            this.SetParamSimple(map, prefix + "UntranslatedText", this.UntranslatedText);
        }

**Comment by zqfan** [comment]
sdk是根据官网文档生成的，新的字段需要出现在官网接口文档后才会出现在sdk中。
