### ISSUE TITLE
asp.net web api 使用sdk报错

### ISSUE THREAD

**Issue by ChobitsSP** [TencentCloud/tencentcloud-sdk-dotnet#22]
未能加载文件或程序集“Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by ChobitsSP** [comment]
.net 4.6.1

**Comment by zqfan** [comment]
SDK依赖的是是Newtonsoft.Json, Version=11.0.1，麻烦用nuget指定依赖版本看看
