### ISSUE TITLE
asp.net web api 应用中调用TBP平台的TextProcess接口时，请求一直处于阻塞状态，没有任何响应

### ISSUE THREAD

**Issue by sunt89** [TencentCloud/tencentcloud-sdk-dotnet#23]
asp.net web api 应用中调用TBP平台的TextProcess接口时，请求一直处于阻塞状态，没有任何响应
相同的代码在控制台应用中可以正常请求。

.net framework 版本： 4.6.1
服务器： IIS 10
SDK版本 3.0.41

**Comment by zqfan** [comment]
已提供同步接口，可以用API Explorer自动生成https://console.cloud.tencent.com/api/explorer。或者直接TextProcessSync这样同步调用即可。
