### ISSUE TITLE
未同步更新的下载地址

### ISSUE THREAD

**Issue by canvaskan** [TencentCloud/tencentcloud-sdk-dotnet#24]
从API Explorer (https://cloud.tencent.com/document/sdk/.Net)
![image](https://user-images.githubusercontent.com/51712573/69872914-c634f880-12f1-11ea-80f9-6a9b1476830d.png)
![image](https://user-images.githubusercontent.com/51712573/69873021-22981800-12f2-11ea-9e97-f1c961ebf311.png)
快速下载地址下载的`tencentcloud-sdk-dotnet.zip`中不包含Iai文件夹

**Comment by zqfan** [comment]
这个是定期刷新的，现在看是有的
