### ISSUE TITLE
sdk在linux下，会发生ssl无法连接的错误

### ISSUE THREAD

**Issue by dogvane** [TencentCloud/tencentcloud-sdk-dotnet#25]
错误消息：”The request with exception: The SSL connection could not be established"

目前使用以下代码跳过验证，但经过测试，baidu的sdk能绕过了，但腾讯的sdk没有办法绕过。
            ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, errors) =>
            {
                Console.WriteLine("on ServerCertificateValidationCallback");
                return true;
            };

服务器版本：ubuntu 16.04
.net 版本: .net core 3.1

**Comment by zqfan** [comment]
需要排查下自己环境下的openssl版本，一种openssl版本太低可能是不支持SNI，另一种可能是证书库有问题
