### ISSUE TITLE
新版本SDK中同时提供了异步接口和同步接口，同步接口统一在异步接口之后添加了Sync后缀，在上述代码中已有样例。

### ISSUE THREAD

**Issue by ckbabby** [TencentCloud/tencentcloud-sdk-dotnet#30]
新版本SDK中同时提供了异步接口和同步接口，同步接口统一在异步接口之后添加了Sync后缀，在上述代码中已有样例。
查看过代码并没有这个方法 需要手动改代码执行InternalRequestSync方法

**Comment by zqfan** [comment]
应该是上个版本出现问题了，在最近的3.0.46版本中已经此问题修复
