### ISSUE TITLE
TencentCloudSDKException

### ISSUE THREAD

**Issue by 1100100** [TencentCloud/tencentcloud-sdk-dotnet#33]
如果api请求失败，sdk默认是抛出TencentCloudSDKException异常，抛出异常本来就是比较耗性能的一个操作，不应该使用Exception来实现业务逻辑，建议在JsonResponseModel类里返回错误码及错误消息

**Comment by zqfan** [comment]
如果api请求失败，正常的逻辑就已经进行不下去了，此时抛出异常也不能说不行吧。况且总是要面临其他异常诸如网络错误。
当前这个版本应该不会在实现机制上改动了，特别是会引起用法差异或者不兼容的。之前的开发人员应该也考虑过，而且我自己看了aws的实现也是要捕获逻辑错误的
