### ISSUE TITLE
Proxy Authentication Failed

### ISSUE THREAD

**Issue by SummerSun** [TencentCloud/tencentcloud-sdk-dotnet#47]
The example of sending sms [Here](https://github.com/TencentCloud/tencentcloud-sdk-dotnet/blob/master/TencentCloudExamples/SendSms.cs) shows we can specify web proxy, but it is of string type. How could I authenticate my proxy then?
```
httpProfile.WebProxy = "WEB_PROXY";
```

**Comment by zqfan** [comment]
I'm not sure if it can work, because i don't have a proxy which needs authentication.
you can try to set proxy like "http://accountname:password@host:port" , make sure it is urlencoded if password has special characters. please feedback here if succeess or not

**Comment by SummerSun** [comment]
Guess it should work, and I need to use the credential carefully. Thanks anyway.
