### ISSUE TITLE
there is no dns-sdk

### ISSUE THREAD

**Issue by ensleep** [TencentCloud/tencentcloud-sdk-dotnet#7]
什么时候可以支持啊，急用

**Comment by zqfan** [comment]
DNS暂时没有对外开放API3.0的接口，因此SDK中没有包含这个产品

**Comment by johnhorse** [comment]
为什么没有云存储模块呢？

**Comment by zqfan** [comment]
@johnhorse 此SDK中只包含在腾讯云官网上的API3.0产品及接口

**Comment by 312030469** [comment]
云点播服务WindowsForms 调用此方法
SearchMediaResponse resp = vodClient.SearchMedia(req).ConfigureAwait(false).GetAwaiter().GetResult();
就会一直等待，无法接收到返回消息是什么原因？

**Comment by zqfan** [comment]
@312030469 winform下使用同步方式调用异步接口确实会卡死，改用异步方式调用接口可也解决问题

**Comment by johnhorse** [comment]
> @312030469 winform下使用同步方式调用异步接口确实会卡死，改用异步方式调用接口可也解决问题

尽量不要在同步方法中调用异步接口，不然的话很容易出现上下文切换出现持续等待内存暴涨现象，不只是winform会出现卡死，在web端并发一上来也会出现卡死

**Comment by zqfan** [comment]
以提供同步接口，可以直接XxxSync这样同步调用，不会再卡死了
