### ISSUE TITLE
能提供下实时音频的sdk调用示例吗

### ISSUE THREAD

**Issue by Glepooek** [TencentCloud/tencentcloud-sdk-dotnet#71]
想实现实时语音合成功能，但我没找到sdk调用示例，像长文本语音合成在APIExplorer上可以找到。实时语音合成官网地址：https://cloud.tencent.com/document/api/1073/34093

**Comment by zqfan** [comment]
https://cloud.tencent.com/document/api/1073/34093
这个接口并非api3.0的（从调用域名判断，根域名不是tencentcloudapi.com），此sdk并不会包含这个接口。可以到控制台提工单给对应的产品咨询下有没有另外提供sdk封装
