### ISSUE TITLE
It is suggested that the project's dependence on Newtonsoft.Json can be adjusted.

### ISSUE THREAD

**Issue by berkerdong** [TencentCloud/tencentcloud-sdk-dotnet#73]
It is recommended to adjust the project’s dependence on Newtonsoft.Json. Since the release of .net core 3, Microsoft has launched a high-performance Json processing module located in System.Text.Json. The performance of this module is relatively high and does not need to rely on third parties. Bag

**Comment by zqfan** [comment]
Usually, there is no necessary for high performance json parse secnario, because API calls must be HTTPS which will cost more than 100ms. And we have to be compatible with .net core 2. If there is no critical case for performance issue, I think newtonsoft.json will be kept for a long time.
