### ISSUE TITLE
TC3-HMAC-SHA256 这是什么意思，我用的表格识别。

### ISSUE THREAD

**Issue by bbhxwl** [TencentCloud/tencentcloud-sdk-dotnet#75]
code:AuthFailure.SignatureFailure message:The provided credentials could not be validated because of exceeding request size limit, please use new signature method `TC3-HMAC-SHA256`.

**Comment by zqfan** [comment]
请求包太大了，要换TC3-HMAC-SHA256这种签名方式调用，sdk可以直接指定的，看readme中的示例就行
