### ISSUE TITLE
TextTranslateRequest.Target 赋值 "kr","jp" 无效

### ISSUE THREAD

**Issue by zicjin** [TencentCloud/tencentcloud-sdk-dotnet#8]
"zh", "ru", "fr" 都可以返回正常内容，但使用"kr","jp" 就会原文返回，没有翻译，也没有抛异常。

**Comment by zqfan** [comment]
sdk无法处理这种业务上的问题，已经转交给具体负责人看了

**Comment by zqfan** [comment]
![image](https://user-images.githubusercontent.com/2180987/50220818-51152f80-03ce-11e9-834d-f8ae8473012f.png)
![image](https://user-images.githubusercontent.com/2180987/50220828-54a8b680-03ce-11e9-9162-17feaf1d5909.png)
看起来能翻译啊，你填的是什么翻译内容？

**Comment by zicjin** [comment]
填的英文，怎样测试的？

**Comment by zicjin** [comment]
应该是业务端修复了，现在测试可以了
